# Generated by Django 2.1 on 2018-08-03 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchandlearn', '0002_auto_20180803_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('difficulty', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='score',
            new_name='composite',
        ),
    ]
