# Generated by Django 2.1 on 2018-08-03 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchandlearn', '0003_auto_20180803_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='definition',
            field=models.CharField(default='defn', max_length=300),
        ),
    ]
