# Generated by Django 2.0.7 on 2018-08-03 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchandlearn', '0004_word_definition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='definition',
        ),
    ]
