# Generated by Django 2.0.7 on 2018-08-04 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchandlearn', '0009_auto_20180803_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='difficulty',
        ),
        migrations.AddField(
            model_name='series',
            name='difficulty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='episode',
            name='subtitle',
            field=models.TextField(default=''),
        ),
    ]
