# Generated by Django 2.2.dev20180804143922 on 2018-08-05 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchandlearn', '0010_auto_20180803_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='number',
            field=models.IntegerField(default=1),
        ),
    ]
