# Generated by Django 2.1 on 2018-08-06 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchandlearn', '0012_auto_20180805_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='image',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='series',
            name='image',
            field=models.CharField(default='', max_length=300),
        ),
    ]
