# Generated by Django 2.1 on 2018-08-06 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchandlearn', '0014_auto_20180806_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='experience',
            field=models.IntegerField(default=0),
        ),
    ]
